### ISSUE TITLE
Map not zooming to Feature Layer after searching in a Geocode Service

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-geocoder#168] opened 2016-12-22 18:54 UTC
I ran into a quirk when using both an ArcGIS Server geocode service and a feature layer search in the same Esri Leaflet Geocoder.  The issue is that after a search has been performed against the Geocode service, when a search is performed against the feature layer, it does not zoom to the feature layer.  This issue occurs whether zoomToResult is set to true or false.  The pertinent links and code are below:

Versions:
- Leaflet = 1.0.2
- Esri Leaflet = 2.0.6
- Esri Leaflet Geocode = 2.2.1

URLs:
- Page: http://gis.ccpa.net/labs/leaflet-upgrade/
- Geocode service: http://gis.ccpa.net/arcgiswebadaptor/rest/services/CompositeLocator/GeocodeServer
- Feature layer: http://gis.ccpa.net/arcgiswebadaptor/rest/services/911/MapServer/7
- Geocode module: http://gis.ccpa.net/labs/leaflet-upgrade/assets/js/geocode.js

**Comment by jgravois** [comment] 2016-12-22 19:07
can you set `zoomToResult: true` in your repro case please?

**Comment by pmacMaps** [comment] 2016-12-22 20:02
@jgravois It's set to **true** now.

**Comment by jgravois** [comment] 2016-12-22 21:11
can you provide a search value that your geocoding service will return results for please?

**Comment by pmacMaps** [comment] 2016-12-22 21:16
15 W High St, Carlisle
100 Gettysburg Pike, Mechanicsburg

**Comment by jgravois** [comment] 2016-12-22 21:35
i'm pretty sure this is another manifestation of the bug i patched in #162 and released in `2.2.2`.  

can you test yourself and confirm?

**Comment by pmacMaps** [comment] 2016-12-27 20:25
I upgraded to version `2.2.2` and am still experiencing the same issue.  However, whenever I tested using the ArcGIS Online World Provider instead of our geocode service, I did not experience an issue.

At this point, it seems like it might be something with our geocode service?

**Comment by jgravois** [comment] 2016-12-27 22:51
> At this point, it seems like it might be something with our geocode service?

no. it turns out this is just another, slightly different, bug in our `featureLayerProvider` that no one noticed until you mixed a custom geocoding service into the equation.

simplest steps to reproduce:
1. add *only* your featureLayerProvider to the geosearch control
2. copy/paste `'a string that doesn't return a single match'` into the search box
3. hit `enter`.
 > as expected, no results are returned
4. type `'the'` into the search box and select `East Pennsboro Elementary` from the list.
> unexpectedly, **no** result is returned.

if you snoop the network traffic you'll see that the last `/query?` request fired includes both the ObjectID of Pennsboro Elementary **and** the original bogus search string.

![screenshot 2016-12-27 14 49 35](https://cloud.githubusercontent.com/assets/3011734/21510023/c294a998-cc43-11e6-8c52-db576da641b9.png)

i've proposed a patch in #170. thanks for the report.

**Closed** 2016-12-30 19:10 UTC
