### ISSUE TITLE
Geocoder returning different data for same record

### ISSUE THREAD

**Issue by lrpatterson** [Esri/esri-leaflet-geocoder#258] opened 2020-10-12 17:38 UTC
**Problem Synopsis:**

I have implemented a basic search widget to allow users to search for properties by address, PIN14, or owner name.  Current if a user searches by owner's name that has multiple properties attached to it.  I get different results based on whether I:

- Type the full owner's name and press enter

- Select the owner's name from the drop down suggestions.

I have inserted a gif below to illustrate what I mean.

**Pressing `Enter` after entering owner's name:** 
![Enter Owner's Name Press Enter](https://user-images.githubusercontent.com/41905851/95775082-ac916b00-0c8f-11eb-8971-c0bb1c8786b2.gif)

**Result after using the drop down suggestions:**
![Select from dropdown suggestions](https://user-images.githubusercontent.com/41905851/95775083-b0bd8880-0c8f-11eb-9bd5-9827d9af294b.gif)

**Basic Example:** 
https://codesandbox.io/s/leaflet-template-forked-5sf72?file=/index.html
Recreate Issue:

1. Enter the following owner into the search input `ZWOLINSKI JO GAIL LF EST` press enter.

2. You should see 3 records returned. This is correct

3. Enter the same name but press the down arrow to select a suggestion and press enter.

4. You should see only 1 record returned when you select `ZWOLINSKI JO GAIL LF EST` as a suggestion.

**Expected result:**  Whether a users presses enter or uses the drop down selection all properties related to that owner should be returned.

**Comment by gavinr** [comment] 2020-10-13 00:50
I don't see a search widget in the codesandbox:
![image](https://user-images.githubusercontent.com/209355/95802837-104a8100-0cee-11eb-9475-bef9295fc062.png)

**Comment by jgravois** [comment] 2020-10-13 00:55
there's a bunch of commented out code in index.js.

the sample was working earlier, but it looks like they've tested out some changes since.

**Comment by lrpatterson** [comment] 2020-10-13 15:24
@jgravois @gavinr  Sorry,  I was testing something forgetting I had linked to this sandbox.  I have reverted so it should be in the same state as before.  Again, sorry.

**Comment by jgravois** [comment] 2020-10-13 16:15
no worries! it happens.

**Comment by jwasilgeo** [comment] 2020-10-13 16:28
In a generic use case, to me this seems to be as intended and designed, where typically there’s a 1:1 relationship between what a user is searching for and want they want to find on the map when using one of the specific suggestions in the drop down list. On the other hand, right, pressing `enter` on the user’s own typed-in string is designed to return all possible results.

What you bring up in an interesting case—where if I follow the nature of your data—you want a specific geocoder suggestion user choice to return all potential matches, rather than only 1 (or only the 1st one). Correct?

**Comment by lrpatterson** [comment] 2020-10-13 19:34
@jwasilgeo That is correct if a user selects an owner, ideally all properties owned should be returned.

**Comment by jgravois** [comment] 2020-10-13 20:25
i can appreciate that you want to take advantage of 'fuzzy search' but you're definitely not describing a typical geocoding workflow.

my gut reaction is that your best bet would be to fire off another query in the background after a suggestion is selected if you're worried about duplicate matches.

happy to hear @jwasilgeo and any other opinions/suggestions too though.

**Comment by lrpatterson** [comment] 2020-10-13 22:49
@jgravois I agree it is out of normal.  Clients request all sorts of things :).

So, you think the best thing is to tie into `requestend` and then take the selected suggestion to get all associated properties?  Is that what you are saying?

**Comment by jgravois** [comment] 2020-10-13 23:08
> tie into `requestend`

i was thinking of [`.on('results')`](http://esri.github.io/esri-leaflet/api-reference/controls/geosearch.html#events) but yes.

**Comment by jgravois** [comment] 2020-10-13 23:11
something else that _might_ work would be to omit the magicKey which typically helps identify the discrete result you want.

you'd have to comment out the line below, recompile the plugin and host it alongside your app.

https://github.com/Esri/esri-leaflet-geocoder/blob/97e878f7193c554f900de48bd915bbf0dcef3d2a/src/Controls/Geosearch.js#L79

**Comment by lrpatterson** [comment] 2020-10-14 00:48
@jgravois Thanks for the idea!  I will have to take some time to test this to see if it is a viable option.

**Comment by jwasilgeo** [comment] 2020-11-17 15:46
I'll close this assuming it was all figured out. Interesting use case and discussion about ideas.

**Closed by jwasilgeo** 2020-11-17 15:46 UTC
Labels: Question
